name: hello-actions

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "building app"
