name: pipeline-skeleton

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage - Start"

  scm-pull:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - run: echo "Stage - SCM pull"

  docker-build:
    runs-on: ubuntu-latest
    needs: scm-pull
    steps:
      - run: echo "Stage - Docker build"

  trivy-scan:
    runs-on: ubuntu-latest
    needs: scm-pull
    steps:
      - run: echo "Stage - Trivy scan"

  bandit-scan:
    runs-on: ubuntu-latest
    needs: scm-pull
    steps:
      - run: echo "Stage - Bandit scan"

  sonarqube:
    runs-on: ubuntu-latest
    needs: scm-pull
    steps:
      - run: echo "Stage - SonarQube"

  docker-push:
    runs-on: ubuntu-latest
    needs: [docker-build, trivy-scan, bandit-scan, sonarqube]
    steps:
      - run: echo "Stage - Docker push"

  unit-test:
    runs-on: ubuntu-latest
    needs: [docker-build, trivy-scan, bandit-scan, sonarqube]
    steps:
      - run: echo "Stage - Unit test"

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-push, unit-test]
    steps:
      - run: echo "Stage - Deploy"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "Stage - Test"

  post-install:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Stage - Post install"
